/* em_door.h — interactive doors: the port's first interactive objects.
 *
 * Native translation of the engine's class-5 double-door actor (decomp
 * repo Extermination/docs/FINDINGS.md "FIRST INTERACTIVE OBJECTS"):
 *
 *   func_001BC350  door behavior (per-frame state machine on the actor's
 *                  sub-state byte +0x05) -> em_door_update()
 *   func_00184BA0  player-side USE SCAN; per-candidate test =
 *                  func_00183EF0 CLASS-5 branch (read in full
 *                  2026-06-11): horizontal dist <= 10 / |dy| <= 8
 *                  (desc D_002755F0) measured from the DOORWAY CENTER
 *                  (hinge + 5 u along the panel for models 3/0x15 — the
 *                  placement origin is the HINGE corner), side test,
 *                  then facing within pi/4 of through-door. No LOS, no
 *                  auto ring (those were the class-7 prefix)
 *                  -> the trigger scan inside em_door_update()
 *   func_001BC300  per-frame articulation + publish/draw
 *                  -> em_door_palette build + the draw accessors
 *
 * Door instances come from the SCENE MANIFEST's doors section (one line
 * per placed door, written by the decomp repo's export_props.py --doors /
 * export_level.py --office0-doors, destination-annotated by
 * export_level.py --door-goto):
 *
 *   door <file.emdl> <x> <y> <z> <yaw> <trigger_radius>
 *       [goto <scene-dir> <sx> <sy> <sz> <syaw>]
 *
 * The OPTIONAL goto tail is the decoded per-area DOOR DESTINATION
 * (FINDINGS "AREA TRANSITION LIFECYCLE": dest table D_0024E140[area]
 * [door_id & 0x7F], static in the boot ELF; spawn = the target
 * sub-state's real spawn-table record, pos + exit yaw). A goto door's
 * transition COMMIT switches the ACTIVE SCENE at full black instead of
 * the same-scene re-place: em_game consumes em_door_goto_pending() and
 * runs em_game_scene_switch() + the spawn placement while the screen is
 * black (the engine's B8==1 area-change shape, minus the audio fade;
 * BGM and the sfx registry persist). <scene-dir> with no '/' is the
 * SIBLING directory name of the current scene dir. 2026-06-11: the
 * shipped links are now the REAL decoded inter-area destinations —
 * AREA01 sub 0 (the drawbridge room, chunk05.n0) is exported as
 * scene_drawbridge, so the office west door (door id 1|0x80 -> AREA01
 * entry 5), office0's m15 door (id 0|0x80 -> AREA01 entry 3) and the
 * drawbridge room's doors 1/3 back into the two office scenes all
 * carry their authentic dest records; the old SYNTHETIC west<->m15
 * wiring is gone. One flagged synthetic remains: the office VENT (the
 * engine's office0 access; its in-room mechanism is overlay-scripted,
 * not a placement object — the manifest carries a flagged vent door
 * line at the suite-corridor position whose goto lands on office0's
 * real spawn entry 5, beside the engine's own class-0x0B trigger
 * record at (43, 3.5, -147)). EM_DOOR_TEST ignores goto tails (it
 * asserts the same-scene re-place geometry).
 *
 * plus one OPTIONAL global sound line (generated by the decomp repo's
 * tools/gen_sfx_registry.py next to the sfx registry; em_door scans
 * scene.txt for it itself — em_game's parser skips unknown keywords):
 *
 *   doorsfx <front-id> <back-id>
 *
 * the D_0024DB80 sound pair the engine patches into the open script
 * (FINDINGS "DOOR SCRIPTS DECODED" s23: pair = D_0024DB80[link >> 8],
 * played as pair[side]; office doors' links are 0x02xx -> pair[2] =
 * 0x3FD front / 0x3FE back). One global line is a FLAGGED
 * simplification — per-door pairs need the manifest door lines to
 * carry the placement LINK halfword (export_props.py owns them).
 * Without the line the legacy placeholder ids fire (em_sfx.h).
 *
 * The EMDL is the door's own articulated model in DOOR-LOCAL space
 * (bone 0 = the door panel, bone 1 = the lock fixture; frame 0 = the
 * captured closed pose). Door files live under <scene>/doors/ so the
 * static scene loader (em_game.c scene_load, which slurps every .emdl in
 * the scene dir) never double-draws them.
 *
 * DOOR TRANSIT — the FULL captured sequence (FINDINGS.md "AREA
 * TRANSITION LIFECYCLE", s22 room-move timeline), natively:
 *
 *   1. use-arm (+0x0B = 4) -> kickoff (func_001BBE40, byte-decoded
 *      2026-06-11): latch the player's side, LOCK player input
 *      (movement + actions ignored, camera frozen —
 *      em_door_input_locked()), snap the player yaw through the door,
 *      and walk the player to the STAGING point = doorway CENTER
 *      (hinge + 5 u along the panel) + 5*n on his own side — both s22
 *      captures reproduce exactly ((104, -247.2) / (62, -225.5)). The
 *      engine SNAPs there in one frame; the port drives the same point
 *      through the scripted MOVE-TO walk (em_door_transit_active ->
 *      em_game player_move), per the walk-to of func_00182F90.
 *   2. OPEN phase (sub 3) — the door script D_0024DE40 (FINDINGS.md
 *      "DOOR SCRIPTS DECODED" s23), run on walk-to arrival: the player
 *      faces the door (the kickoff yaw snap) and plays anim 0x45
 *      (front) / 0x43 (back) at rate 1.0 through em_game's scripted-
 *      anim mailbox (op 0x0A sub 0) while the door clip + sound run
 *      (op 0x0B sub 6; captured clip window 77..97 vsyncs); the script
 *      waits 90 (front) / 70 (back) frames (op 0x02 STOP) -> commit
 *      (sub 4, func_001BC240 -> func_001BC150): 64-frame fade-out
 *      (func_001AEDE0(4,0) -> em_frame_fade_start). Room moves do NOT
 *      fade audio (only area changes do — s22).
 *   3. while black: the player is RE-PLACED at the spawn point behind
 *      the door (door - 5*n on the far side, exit yaw — the spawn-table
 *      records flank their door at +-5 with exit pose); consumed by
 *      em_game through em_door_warp_pending(). The door starts closing
 *      (the engine re-arms when the request byte B8 clears, right after
 *      the re-place) and a 64-frame fade-in starts.
 *   4. fade-in complete -> input UNLOCKED; the door finishes its close
 *      and re-arms (sub 5 -> 0).
 *
 * FIDELITY NOTES (remaining port deviations, each flagged in em_door.c):
 *  - The engine triggers doors on WALK-INTO (player locomotion state
 *    0x2D = pressing forward, no button); the port requires the CROSS
 *    button until the action-state machine is translated. (The old
 *    2-u auto ring and LOS pocket exemption are GONE — 2026-06-11: the
 *    class-5 use-scan branch has neither.)
 *  - The engine SNAPs the player to the staging point; the port walks
 *    the same point through the scripted MOVE-TO.
 *  - The hinged-model flag (doorway-center offset) rides the exporter's
 *    doors/door_mXX.emdl filename, not a manifest field.
 *  - Non-m03-family doors (m17/m09 sliders) run this same m03 state
 *    machine as a stand-in for their variant brain func_001BB860.
 *  - Every transit is treated as the INTRA-AREA room move (request mode
 *    B8 == 2): same-scene re-place, no audio fade, actors/overlay kept.
 *    The inter-area path (B8 == 1: audio fade + overlay/asset/actor-pool
 *    reload) needs the native area loader — goto doors approximate it
 *    with the scene switch (em_door_goto_pending).
 *
 * COLLISION: the engine gives placed objects collision through per-uid
 * AABB records in the area state blob (movable-hull set, mask bit 0) —
 * NOT through the static world, and the office EMCL bake confirms both
 * doorways are open in the static sets. em_door_probe() is the native
 * movable-hull stand-in: a segment-vs-AABB test against every door that
 * is not fully open, consumed by the player move probe (em_game.c). The
 * camera solver keeps the engine's own mask 6 (static only), so the
 * camera sees through doors exactly like the original.
 */
#ifndef EM_DOOR_H
#define EM_DOOR_H

#include <stdint.h>

#include "em_gfx.h"
#include "game/em_collision.h"
#include "game/em_frame.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Instance-list capacity (the office has 2; the render chain in
 * em_game.c sizes its draw slots with this). */
#define EM_DOOR_MAX 8

/* Door sub-states — the ENGINE's values for the actor byte +0x05
 * (jtbl_0026E1C0). 1/2 (the locked sequence, model 0x15 security doors)
 * need the unlock bitmask D_00810841 and are not in the port yet. */
enum {
    EM_DOOR_CLOSED  = 0,
    EM_DOOR_OPENING = 3,
    EM_DOOR_OPEN    = 4,   /* one-frame transition COMMIT (func_001BC150) */
    EM_DOOR_CLOSING = 5    /* transition pending: fade-out -> re-place ->
                            * close + fade-in -> re-arm (engine sub 5) */
};

/* Reset the instance list (boot / scene reload). Does not free GPU
 * resources — pair with em_door_shutdown for that. */
void em_door_reset(void);

/* Add one door instance from a manifest line. `file` is relative to
 * `scene_dir` (e.g. "doors/door_m03.emdl"); the model is loaded and
 * uploaded once per distinct file. Returns 0 on success. */
int em_door_add(EmGfx *gfx, const char *scene_dir, const char *file,
                const float pos[3], float yaw, float radius);

/* Attach a manifest goto tail to door `i` (the last em_door_add):
 * `target` is the destination scene dir (sibling name or path), `spawn`/
 * `spawn_yaw` the decoded arrival spawn record. Returns 0 on success. */
int em_door_set_goto(int i, const char *target, const float spawn[3],
                     float spawn_yaw);

/* One-shot SCENE-SWITCH request — the goto-door analog of
 * em_door_warp_pending(): returns 1 exactly once, at fade-out completion
 * (screen fully black), with the target scene dir copied into `dir` and
 * the arrival spawn pose. em_game.c consumes it (em_game_scene_switch +
 * player/camera placement while black); the fade-in and the input
 * unlock keep running across the reload (the transit-wide lock survives
 * em_door_scene_clear). */
int em_door_goto_pending(char *dir, unsigned dir_size, float out_pos[3],
                         float *out_yaw);

/* Scene switch teardown: free every door instance + model/mesh like
 * em_door_shutdown, but PRESERVE the transit-wide input lock and the
 * armed fade-in unlock (the switch happens mid-transit, while black).
 * The per-scene doorsfx pair is cleared (the new scene.txt is scanned
 * by its own first em_door_add). */
void em_door_scene_clear(EmGfx *gfx);

/* Per-frame update: trigger scan (the func_00184BA0 use scan against
 * this player position/facing + the frame input block) and every door's
 * state machine + articulation palette. `coll` (may be NULL) is the
 * static world used for the engine's line-of-sight gate. Call once per
 * gameplay frame, at the world-services slot (func_001AFD70). */
void em_door_update(const EmCollision *coll, const float player_pos[3],
                    float player_yaw, const EmFrameInput *in);

/* Active door-transit MOVE-TO (func_001BBE40's player walk-to; the
 * engine's gameplay-frame selector 3 "door transit" variant). While it
 * returns 1, the player WALKS to `out_target` (the staging point) with
 * yaw snapped to `out_yaw` through the normal locomotion path,
 * collision-free — this is how the engine carries the player across the
 * statically sealed doorway boundary planes (the engine snaps; the port
 * walks the same scripted move). Consumed by em_game.c player_move. */
int em_door_transit_active(float out_target[3], float *out_yaw);

/* INPUT LOCK — nonzero from the transit kickoff until the fade-in
 * completes: player movement + actions are ignored (player_move and the
 * weapon machine read neutral input) and the camera is frozen.
 * em_game.c consumes it every frame; tests query it directly. */
int em_door_input_locked(void);

/* One-shot RE-PLACE request: returns 1 exactly once, at fade-out
 * completion (screen fully black), with the spawn point behind the door
 * (door -+ 5*normal, far side) and the exit yaw — the documented
 * spawn-table re-place. em_game.c consumes it (sets the player position
 * + yaw and re-seats the camera while black). */
int em_door_warp_pending(float out_pos[3], float *out_yaw);

/* Draw accessors for the render chain. */
int  em_door_count(void);
void em_door_draw(int i, EmGfxMesh **mesh, const float **palette,
                  uint32_t *bone_count);

/* Movable-hull segment probe (collision-set bit 0 stand-in): nearest
 * blocking-door AABB hit on [from, to], or 0. A fully OPEN door does not
 * block (the engine clears the object's collision state word). */
int em_door_probe(const float from[3], const float to[3], EmCollHit *hit);

/* Introspection (debug / self-tests). */
int  em_door_state(int i);
void em_door_pos(int i, float out[3]);

/* Destroy GPU meshes + free models. */
void em_door_shutdown(EmGfx *gfx);

#ifdef __cplusplus
}
#endif

#endif /* EM_DOOR_H */
