/* em_door.h — interactive doors: the port's first interactive objects.
 *
 * Native translation of the engine's class-5 double-door actor (decomp
 * repo Extermination/docs/FINDINGS.md "FIRST INTERACTIVE OBJECTS"):
 *
 *   func_001BC350  door behavior (per-frame state machine on the actor's
 *                  sub-state byte +0x05) -> em_door_update()
 *   func_00184BA0  player-side USE SCAN; per-candidate test =
 *                  func_00183EF0 CLASS-5 branch (read in full
 *                  2026-06-11): horizontal dist <= 10 / |dy| <= 8
 *                  (desc D_002755F0) measured from the DOORWAY CENTER
 *                  (hinge + 5 u along the panel for models 3/0x15 — the
 *                  placement origin is the HINGE corner), side test,
 *                  then facing within pi/4 of through-door. No LOS, no
 *                  auto ring (those were the class-7 prefix)
 *                  -> the trigger scan inside em_door_update()
 *   func_001BC300  per-frame articulation + publish/draw
 *                  -> em_door_palette build + the draw accessors
 *
 * Door instances come from the SCENE MANIFEST's doors section (one line
 * per placed door, written by the decomp repo's export_props.py --doors /
 * export_level.py --office0-doors, destination-annotated by
 * export_level.py --door-goto):
 *
 *   door <file.emdl> <x> <y> <z> <yaw> <trigger_radius>
 *       [goto <scene-dir> <sx> <sy> <sz> <syaw>]
 *
 * The OPTIONAL goto tail is the decoded per-area DOOR DESTINATION
 * (FINDINGS "AREA TRANSITION LIFECYCLE": dest table D_0024E140[area]
 * [door_id & 0x7F], static in the boot ELF; spawn = the target
 * sub-state's real spawn-table record, pos + exit yaw). A goto door's
 * transition COMMIT switches the ACTIVE SCENE at full black instead of
 * the same-scene re-place: em_game consumes em_door_goto_pending() and
 * runs em_game_scene_switch() + the spawn placement while the screen is
 * black (the engine's B8==1 area-change shape, minus the audio fade;
 * BGM and the sfx registry persist). <scene-dir> with no '/' is the
 * SIBLING directory name of the current scene dir. 2026-06-11: the
 * shipped links are now the REAL decoded inter-area destinations —
 * AREA01 sub 0 (the drawbridge room, chunk05.n0) is exported as
 * scene_drawbridge, so the office west door (door id 1|0x80 -> AREA01
 * entry 5), office0's m15 door (id 0|0x80 -> AREA01 entry 3) and the
 * drawbridge room's doors 1/3 back into the two office scenes all
 * carry their authentic dest records; the old SYNTHETIC west<->m15
 * wiring is gone. One flagged synthetic remains: the office VENT (the
 * engine's office0 access; its in-room mechanism is overlay-scripted,
 * not a placement object — the manifest carries a flagged vent door
 * line at the suite-corridor position whose goto lands on office0's
 * real spawn entry 5, beside the engine's own class-0x0B trigger
 * record at (43, 3.5, -147)). EM_DOOR_TEST ignores goto tails (it
 * asserts the same-scene re-place geometry).
 *
 * plus one OPTIONAL global sound line (generated by the decomp repo's
 * tools/gen_sfx_registry.py next to the sfx registry; em_door scans
 * scene.txt for it itself — em_game's parser skips unknown keywords):
 *
 *   doorsfx <front-id> <back-id>
 *
 * the D_0024DB80 sound pair the engine patches into the open script
 * (FINDINGS "DOOR SCRIPTS DECODED" s23: pair = D_0024DB80[link >> 8],
 * played as pair[side]; office doors' links are 0x02xx -> pair[2] =
 * 0x3FD front / 0x3FE back). One global line is a FLAGGED
 * simplification — per-door pairs need the manifest door lines to
 * carry the placement LINK halfword (export_props.py owns them).
 * Without the line the legacy placeholder ids fire (em_sfx.h).
 *
 * The EMDL is the door's own articulated model in DOOR-LOCAL space
 * (bone 0 = the door panel, bone 1 = the lock fixture; frame 0 = the
 * captured closed pose). Door files live under <scene>/doors/ so the
 * static scene loader (em_game.c scene_load, which slurps every .emdl in
 * the scene dir) never double-draws them.
 *
 * DOOR TRANSIT — the FULL captured sequence (FINDINGS.md "AREA
 * TRANSITION LIFECYCLE", s22 room-move timeline), natively:
 *
 *   1. use-arm (+0x0B = 4) -> kickoff (func_001BBE40, byte-decoded
 *      2026-06-11): latch the player's side, LOCK player input
 *      (movement + actions ignored, camera frozen — the two-lock split
 *      below: em_door_movement_locked / em_door_menu_locked, both set
 *      here), snap the player yaw through the door,
 *      and walk the player to the STAGING point = doorway CENTER
 *      (hinge + 5 u along the panel) + 5*n on his own side — both s22
 *      captures reproduce exactly ((104, -247.2) / (62, -225.5)). The
 *      engine SNAPs there in one frame; the port drives the same point
 *      through the scripted MOVE-TO walk (em_door_transit_active ->
 *      em_game player_move), per the walk-to of func_00182F90.
 *   2. OPEN phase (sub 3) — the door script D_0024DE40 (FINDINGS.md
 *      "DOOR SCRIPTS DECODED" s23), run on walk-to arrival: the player
 *      faces the door (the kickoff yaw snap) and plays anim 0x45
 *      (front) / 0x43 (back) at rate 1.0 through em_game's scripted-
 *      anim mailbox (op 0x0A sub 0) while the door clip + sound run
 *      (op 0x0B sub 6; captured clip window 77..97 vsyncs); the script
 *      waits 90 (front) / 70 (back) frames (op 0x02 STOP) -> commit
 *      (sub 4, func_001BC240 -> func_001BC150): 64-frame fade-out
 *      (func_001AEDE0(4,0) -> em_frame_fade_start). Room moves do NOT
 *      fade audio (only area changes do — s22).
 *   3. while black: the player is RE-PLACED at the spawn point behind
 *      the door (door - 5*n on the far side, exit yaw — the spawn-table
 *      records flank their door at +-5 with exit pose); consumed by
 *      em_game through em_door_warp_pending(). The door starts closing
 *      (the engine re-arms when the request byte B8 clears, right after
 *      the re-place) and a 64-frame fade-in starts. The re-place ALSO
 *      starts the ARRIVAL WALK-OUT (below).
 *   4. ARRIVAL WALK-OUT (decoded 2026-06-11 — the engine's player state
 *      5/1, dispatcher func_0015B610 -> handler func_00183250): the
 *      re-place state func_001AE040[4] calls func_001B07C0(1), which
 *      reads the spawn record's +0x14 byte (1 in every decoded record)
 *      and puts the player actor in state 5 sub 1 — the scripted
 *      walk-out. Its sub-machine (+0x06 phases):
 *        phase 0 (1 frame): request the locomotion clip at locIdx 2
 *                 (mode-1 anim table D_00248AB0[1][family*4+2]: family 0
 *                 unarmed -> id 2 = RUN; armed families -> the scripted
 *                 walks 0x4D/0x4E), ramp +0x38 = 0.3 u/tick
 *                 (D_00248870[2]), timer 0x32
 *        phase 1 (50 frames): clip plays, NO translation (the mover
 *                 func_00178B90 is not called) — hidden under the
 *                 fade-in for its first ~64 frames
 *        phase 2 (30 frames): mover runs at 0.3 u/tick along the spawn
 *                 yaw
 *        phase 3 (30 frames): mover runs while the ramp decays
 *                 0.0113636/frame (0x3C3A2E8C) to 0 (~26 frames), the
 *                 base idle is requested (blend 12) — the player
 *                 decelerates to a stop ~12.8 u out from the spawn
 *        exit: player state 1/0, action +0x1F0 = 0, spad 3B8D cleared.
 *      The walk-out is UNINTERRUPTIBLE: state 5 never reads the stick.
 *      Total ~111 frames from the re-place.
 *
 * THE TWO LOCKS (decoded 2026-06-11 — they are SEPARATE systems):
 *
 *   MOVEMENT lock — the player actor's STATE machine. From the use-arm
 *   the script/transit owns the player (scripted mode spad 0x70003B8D
 *   = 3 routes frames to the cutscene variant func_001AE6B0, which
 *   never runs free movement), and on arrival state 5/1 (the walk-out
 *   above) ignores the stick until its phases complete. Natively:
 *   em_door_movement_locked() — kickoff until the walk-out ends.
 *
 *   MENU lock — the frame poll func_001AE7E0 (the gate that returns 2
 *   = "open the status screen" on Triangle/Start). It refuses while:
 *     - a transition request is pending (D_008106B8/B9 != 0),
 *     - the FADE machine is not idle (D_0028A9A0 — the +0xC0 sub-state
 *       — != 0: fade-out 3, hold-black 2, fade-in 1),
 *     - scripted mode is active (spad 0x70003B8D != 0).
 *   On ARRIVAL the re-place state's first call func_001AFCF0 CLEARS
 *   spad 3B8D (while the screen is still black), so the only menu gate
 *   left is the fade-in: Triangle/Start works again the moment the
 *   fade-in completes (~frame 64 of the ~111-frame walk-out — "about
 *   halfway through", while movement is still locked). Natively:
 *   em_door_menu_locked() — kickoff until the fade-in completes.
 *   em_hud gates its open toggle on it (the func_001AE7E0 stand-in).
 *
 * SLIDERS (m17/m09 — the variant brain func_001BB860, DECODED
 * 2026-06-11; closes the s32 "variant lifecycle unread" flag): sliding
 * doors do NOT run the m03 transit. The trigger is the same +0x0B
 * use-arm — set by WALKING INTO the door (no button) — and the trigger
 * sub func_001BB560 then snaps the player yaw through the door, stages
 * him at door_pos - 6.0 * forward (func_00182F90 instant translate; 6.0
 * — not the m03 5.0) and queues the OPEN script D_0024D900: scripted-
 * mode enter (input lock, NO fade), chase-camera cue, ONE positional
 * door sound, the NATIVE SLIDE func_001BB400 (panels part 0.2 u/frame
 * to 9.0 u — the EMDL's baked 46-frame clip), then op01-sub8 = a
 * scripted player WALK-THROUGH (walk clip; there is NO player
 * door-gesture anim anywhere in the slider script — the user-verified
 * PCSX2 behavior: walk at the door, the panels part, you walk
 * through). Lock-gated placements (flags2 0x16/0x17/0x3E vs the
 * D_00810841 unlock bits) run a LOCKED script (camera + VO, no motion)
 * — not in the port (no lock bitmask, flagged). See em_door.c "SLIDER
 * (m17/m09) VARIANT BRAIN" for the full decode + port mapping.
 *
 * FIDELITY NOTES (remaining port deviations, each flagged in em_door.c):
 *  - The engine triggers ALL doors on WALK-INTO (player locomotion
 *    state 0x2D = pressing forward, no button); the port's HINGED m03
 *    family still requires the CROSS button until the action-state
 *    machine is translated. SLIDERS arm on the walk-into itself
 *    (stick-push + the class-5 window), per the decoded variant brain.
 *    (The old 2-u auto ring and LOS pocket exemption are GONE —
 *    2026-06-11: the class-5 use-scan branch has neither.)
 *  - The engine SNAPs the player to the staging point; the port walks
 *    the same point through the scripted MOVE-TO.
 *  - The hinged/slider model flags ride the exporter's
 *    doors/door_mXX.emdl filename, not a manifest field.
 *  - Every transit is treated as the INTRA-AREA room move (request mode
 *    B8 == 2): same-scene re-place, no audio fade, actors/overlay kept.
 *    The inter-area path (B8 == 1: audio fade + overlay/asset/actor-pool
 *    reload) needs the native area loader — goto doors approximate it
 *    with the scene switch (em_door_goto_pending). A goto SLIDER reuses
 *    that same commit after its walk-through (the native slider
 *    commit/fade interleave is unread — flagged); a plain slider ends
 *    its script with the player free on the far side, stays parted,
 *    and re-closes (clip reversed, the s32 flag) when the player
 *    leaves the scan radius.
 *
 * COLLISION: the engine gives placed objects collision through per-uid
 * AABB records in the area state blob (movable-hull set, mask bit 0) —
 * NOT through the static world, and the office EMCL bake confirms both
 * doorways are open in the static sets. em_door_probe() is the native
 * movable-hull stand-in: a segment-vs-AABB test against every door that
 * is not fully open, consumed by the player move probe (em_game.c). The
 * camera solver keeps the engine's own mask 6 (static only), so the
 * camera sees through doors exactly like the original.
 *
 * THE LOCKED SEQUENCE (engine subs 1/2 — ported 2026-06-11; FINDINGS
 * "DOOR SCRIPTS DECODED" s23 script D_0024DEC0 + the s45 clip-motion
 * verdicts + the s53/s56 locked-look camera):
 *
 *   GATE  func_001BC350 sub-state 0, model 0x15 ("security door"):
 *         unlock bitmask `D_00810841[area] & (1 << door_id)` — bit SET
 *         opens normally (func_001BBE40 mode 0), bit CLEAR runs the
 *         LOCKED TRY (mode 1 -> sub 1). D_00810841 is BSS: every
 *         lock-gated door starts LOCKED until a game event (door
 *         panel / keycard script) sets its bit. Natively the manifest
 *         door line carries the decoded gate as a `locked` token
 *         (export_level.py --door-locked) and em_door_unlock() is the
 *         bit-set event. Slider lock gates (flags2 0x16/0x17/0x3E,
 *         script D_0024DA40 = camera + VO only) have no exported
 *         placement; a `locked` slider runs the hinged refusal minus
 *         anim/clip/rattle (FLAGGED approximation, unexercised).
 *
 *   SCRIPT D_0024DEC0 (queued by func_001BBE40 mode 1, after the same
 *   side-latch/yaw-snap/staging walk as the open kickoff):
 *     op07 sub2   scripted-mode enter (both locks; the fade-arm variant
 *                 func_001AEB60(4) is a fade-IN arm — no visual effect
 *                 on a bright screen, not ported)
 *     op09        func_001BBBF0 locked-look camera CUT: target = door
 *                 + 8 u to the HANDLE side (door-yaw left) + 10 up,
 *                 eye = target - 13 along the live camera yaw at
 *                 door.y + 12 (em_game consumes em_door_locked_look)
 *     op0A sub0   player anim 0x46 front / 0x44 back rate 1.0 — the
 *                 directory-verified TRY-THE-HANDLE-AND-FAIL gestures
 *                 (200 f, limbs only, exact return to rest; the
 *                 2026-06-11 bake re-verified peak node deviation
 *                 5.4/6.6 u at f64-68)
 *     op0B sub0   DOOR clip engine id 3 front / 1 back — the lock-
 *                 fixture jiggle (s30: 200 f, panel still, fixture
 *                 rattle peaks ~f60-110, settles to rest), no sound
 *     op02        wait 60 frames
 *     op17 sub0   positional sound 0x3F2 — the LOCKED RATTLE (fires
 *                 exactly as the fixture motion peaks)
 *     op09        func_001BBAE0 locked "VO" — decoded 2026-06-11: a
 *                 TEXT-ONLY RADIO MESSAGE (link bits 0-5 ->
 *                 jtbl_0026E1A0 -> global message line; every shipped
 *                 line's voice-cue field is -1, so there is NO audio).
 *                 The optional scene.txt `lockedvo <id-hex>` line (the
 *                 gen_sfx_registry.py decode emits it only if a real
 *                 cue ever resolves) plays through em_sfx here;
 *                 absent = silence (the radio text machine is not
 *                 ported — flagged)
 *     op0B sub1   wait door clip end (200 f — dominates the VO wait)
 *   then sub 1 queues D_0024DBC0 = op07 sub4 EXIT: restore camera +
 *   control (-> sub 2 -> re-arm CLOSED). The door never opens, no
 *   fade, no warp; the player is left standing at the staging point
 *   (the engine snapped him there; the port walked him).
 */
#ifndef EM_DOOR_H
#define EM_DOOR_H

#include <stdint.h>

#include "em_gfx.h"
#include "game/em_collision.h"
#include "game/em_frame.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Instance-list capacity (the office has 2; the render chain in
 * em_game.c sizes its draw slots with this). */
#define EM_DOOR_MAX 8

/* Door sub-states — the ENGINE's values for the actor byte +0x05
 * (jtbl_0026E1C0). 1/2 = the LOCKED sequence (model 0x15 security
 * doors vs the unlock bitmask D_00810841 — ported 2026-06-11, see
 * "THE LOCKED SEQUENCE" in the header comment). */
enum {
    EM_DOOR_CLOSED     = 0,
    EM_DOOR_LOCKED_TRY = 1, /* locked-try script D_0024DEC0 running
                             * (engine sub 1: clip pump + script) */
    EM_DOOR_LOCKED_END = 2, /* finish script D_0024DBC0 ran (engine sub
                             * 2: restore + re-arm next frame) */
    EM_DOOR_OPENING    = 3,
    EM_DOOR_OPEN       = 4, /* one-frame transition COMMIT (func_001BC150) */
    EM_DOOR_CLOSING    = 5  /* transition pending: fade-out -> re-place ->
                             * close + fade-in -> re-arm (engine sub 5) */
};

/* Reset the instance list (boot / scene reload). Does not free GPU
 * resources — pair with em_door_shutdown for that. */
void em_door_reset(void);

/* Add one door instance from a manifest line. `file` is relative to
 * `scene_dir` (e.g. "doors/door_m03.emdl"); the model is loaded and
 * uploaded once per distinct file. Returns 0 on success. */
int em_door_add(EmGfx *gfx, const char *scene_dir, const char *file,
                const float pos[3], float yaw, float radius);

/* Attach a manifest goto tail to door `i` (the last em_door_add):
 * `target` is the destination scene dir (sibling name or path), `spawn`/
 * `spawn_yaw` the decoded arrival spawn record. Returns 0 on success. */
int em_door_set_goto(int i, const char *target, const float spawn[3],
                     float spawn_yaw);

/* Mark door `i` LOCK-GATED (the manifest `locked` token — the decoded
 * model-0x15 / flags2 gate vs the BSS unlock bitmask D_00810841, which
 * is all-zero at boot: the door starts LOCKED). Returns 0 on success. */
int em_door_set_locked(int i);

/* The unlock event — the native D_00810841[area] |= 1 << door_id (the
 * engine's door-panel / keycard scripts write it). A locked door
 * em_door_unlock'ed opens normally on the next use-arm. */
void em_door_unlock(int i);

/* 1 while door `i` still refuses (lock-gated and not yet unlocked). */
int em_door_is_locked(int i);

/* LOCKED-LOOK camera feed (script D_0024DEC0 record 2 = op 0x09 ->
 * func_001BBBF0): returns 1 while a locked-try script holds the
 * locked-look placement (arrival .. finish), with the door's placement
 * pos/yaw for the handle-side math. em_game.c's camera consumes it (the
 * cut on the rising edge, the op07-sub4 restore on the falling one). */
int em_door_locked_look(float out_door_pos[3], float *out_door_yaw);

/* Locked-rattle play count (op 0x17 sub 0, sound 0x3F2) — test/debug
 * introspection (EM_LOCKED_TEST asserts exactly one per refusal). */
int em_door_rattles(void);

/* One-shot SCENE-SWITCH request — the goto-door analog of
 * em_door_warp_pending(): returns 1 exactly once, at fade-out completion
 * (screen fully black), with the target scene dir copied into `dir` and
 * the arrival spawn pose. em_game.c consumes it (em_game_scene_switch +
 * player/camera placement while black); the fade-in and the input
 * unlock keep running across the reload (the transit-wide lock survives
 * em_door_scene_clear). */
int em_door_goto_pending(char *dir, unsigned dir_size, float out_pos[3],
                         float *out_yaw);

/* Scene switch teardown: free every door instance + model/mesh like
 * em_door_shutdown, but PRESERVE the transit-wide state (both locks,
 * the armed fade-in unlock, and the arrival walk-out — the switch
 * happens mid-transit, while black, and the walk-out runs in the NEW
 * scene exactly like the engine's player state surviving the area
 * load). The per-scene doorsfx pair is cleared (the new scene.txt is
 * scanned by its own first em_door_add). */
void em_door_scene_clear(EmGfx *gfx);

/* Per-frame update: trigger scan (the func_00184BA0 use scan against
 * this player position/facing + the frame input block) and every door's
 * state machine + articulation palette. `coll` (may be NULL) is the
 * static world used for the engine's line-of-sight gate. Call once per
 * gameplay frame, at the world-services slot (func_001AFD70). */
void em_door_update(const EmCollision *coll, const float player_pos[3],
                    float player_yaw, const EmFrameInput *in);

/* Active door-transit MOVE-TO (func_001BBE40's player walk-to; the
 * engine's gameplay-frame selector 3 "door transit" variant). While it
 * returns 1, the player WALKS to `out_target` (the staging point) with
 * yaw snapped to `out_yaw` through the normal locomotion path,
 * collision-free — this is how the engine carries the player across the
 * statically sealed doorway boundary planes (the engine snaps; the port
 * walks the same scripted move). Consumed by em_game.c player_move. */
int em_door_transit_active(float out_target[3], float *out_yaw);

/* THE TWO TRANSIT LOCKS (the decoded split — see "THE TWO LOCKS" in the
 * header comment; the old single em_door_input_locked() is GONE):
 *
 * MOVEMENT lock — nonzero from the transit kickoff until the arrival
 * WALK-OUT completes (player state 5/1, func_00183250 phases): player
 * movement + actions are ignored (player_move and the weapon machine
 * read neutral input) and the camera auto-orient is suppressed.
 * em_game.c consumes it every frame; tests query it directly. */
int em_door_movement_locked(void);

/* MENU lock — nonzero from the transit kickoff until the FADE-IN
 * completes (the func_001AE7E0 gate: pending request / fade machine
 * D_0028A9A0 != 0 / scripted spad 3B8D; on arrival 3B8D is already
 * cleared at the re-place, so the fade-in is the last gate). em_hud
 * gates the Triangle/Start status-screen toggle on it — the menu
 * opens mid-walk-out, exactly like the engine. */
int em_door_menu_locked(void);

/* ARRIVAL WALK-OUT drive (player state 5/1, func_00183250): returns 1
 * while the walk-out runs, with the walk direction (the spawn record's
 * exit yaw) and THIS frame's commanded translation speed in units/sec
 * (phase 1: 0 — the clip plays in place; phase 2: 18 u/s = the engine's
 * 0.3 u/tick locIdx-2 speed; phase 3: the decaying ramp). em_game.c
 * player_move consumes it INSTEAD of stick input (uninterruptible),
 * driving the locomotion clip from the speed. Phases advance in
 * em_door_update; the state survives a goto scene switch
 * (em_door_scene_clear), exactly like the engine's player state. */
int em_door_walkout_active(float *out_yaw, float *out_speed);

/* One-shot RE-PLACE request: returns 1 exactly once, at fade-out
 * completion (screen fully black), with the spawn point behind the door
 * (door -+ 5*normal, far side) and the exit yaw — the documented
 * spawn-table re-place. em_game.c consumes it (sets the player position
 * + yaw and re-seats the camera while black). */
int em_door_warp_pending(float out_pos[3], float *out_yaw);

/* Draw accessors for the render chain. */
int  em_door_count(void);
void em_door_draw(int i, EmGfxMesh **mesh, const float **palette,
                  uint32_t *bone_count);

/* Movable-hull segment probe (collision-set bit 0 stand-in): nearest
 * blocking-door AABB hit on [from, to], or 0. A fully OPEN door does not
 * block (the engine clears the object's collision state word). */
int em_door_probe(const float from[3], const float to[3], EmCollHit *hit);

/* Introspection (debug / self-tests). */
int  em_door_state(int i);
void em_door_pos(int i, float out[3]);

/* Destroy GPU meshes + free models. */
void em_door_shutdown(EmGfx *gfx);

#ifdef __cplusplus
}
#endif

#endif /* EM_DOOR_H */
